#ifndef _INCLUDE_AMXX_VERSION_INFORMATION_H_
#define _INCLUDE_AMXX_VERSION_INFORMATION_H_

#define AMXX_BUILD_TAG        "standalone"
#define AMXX_BUILD_LOCAL_REV  "0"
#define AMXX_BUILD_CSET       "0"
#define AMXX_BUILD_MAJOR      "1"
#define AMXX_BUILD_MINOR      "10"
#define AMXX_BUILD_RELEASE    "0"

#define AMXX_BUILD_UNIQUEID AMXX_BUILD_LOCAL_REV ":" AMXX_BUILD_CSET

#define AMXX_VERSION_STRING   AMXX_BUILD_MAJOR "." AMXX_BUILD_MINOR "." AMXX_BUILD_RELEASE "-" AMXX_BUILD_TAG
#define AMXX_VERSION_FILE     1,10,0,0

#define AMXX_BUILD_TIMESTAMP  __DATE__ " " __TIME__

#define AMXX_VERSION      AMXX_VERSION_STRING
#define AMXX_BUILD_ID     AMXX_BUILD_UNIQUEID
#define AMXX_BUILD_TIME   AMXX_BUILD_TIMESTAMP

#endif /* _INCLUDE_AMXX_VERSION_INFORMATION_H_ */
